### ISSUE TITLE
margin-bottom shouldn't be 0 when a p is inside of a data-before or data-after div

### ISSUE THREAD

**Issue by dmalan** [cs50/jekyll-theme-cs50#118]
<img width="449" alt="Screen Shot 2020-04-01 at 6 57 34 PM" src="https://user-images.githubusercontent.com/788678/78194288-b74e8600-744a-11ea-8c9f-5ac9232d47c3.png">

**Comment by ruben676** [comment]
I'm so lost in what this means.. please help 
S.O.S

**Comment by dmalan** [comment]
No worries, all set!
