### ISSUE TITLE
Uncaught Exception / Site Fails when URLs include Text Fragments

### ISSUE THREAD

**Issue by latefield** [cs50/jekyll-theme-cs50#157]
### Description

This commit, 96c05a294662d2be6d352dc6ce0d360cb968fdbe, introduced support for Chrome's proposed web standard for Text Fragments. The commit works as expected and highlighting text updates the URL. 

However, if they copy the updated URL and load it in a non-Chromium browser (or if they click refresh) then an uncaught exception occurs.  The below error was produced by the JS console in Firefox. 

```

Uncaught Error: Syntax error, unrecognized expression: #:~:text=mines%20the%20design%20and%20implementation%20of%20web%20applications%20with%20Python,%20JavaScript,%20and%20SQL%20using%20frameworks%20like%20Django,%20React,%20and%20Bootstrap.%20Topics%20include%20database%20design,%20scalability,%20s
    jQuery 7
    <anonymous> https://cs50.harvard.edu/summer/web/2021/assets/jekyll-theme-cs50.js?1624849408:466
    jQuery 7
    <anonymous> https://cs50.harvard.edu/summer/web/2021/assets/jekyll-theme-cs50.js?1624849408:480
    jQuery 8
    <anonymous> https://cs50.harvard.edu/summer/web/2021/assets/jekyll-theme-cs50.js?1624849408:17

```
### How to Reproduce

You can easily reproduce this by taking any URL generated from a CS50 Jekyll site with Text Fragments and attempting to load it in a non-Chromium browser. [Here is a link for reference.](https://cs50.harvard.edu/summer/web/2021/#:~:text=This%20course%20examines%20the%20design%20and%20implementation%20of%20web%20applications%20with%20Py)

I can personally confirm that this occurs on:

- Firefox 89.0.2 (64-bit) on MacOS 10.15.7
- Safari 14.1.1 on MacOS 10.15.7
- Firefox 89 on Windows 10

### Potential Fix

The issue appears to be related to the following function:
https://github.com/cs50/jekyll-theme-cs50/blob/4804023cb98c99b08b0f91d595ce7c00346ac2f3/assets/jekyll-theme-cs50.js#L459

In this function you attempt to navigate to an element by ID, with the ID derived from the URL. It seems like you could check to see if window.location.hash.slice(1, 4) == ":~:" and if so return False, matching the behavior that happens when there is no hash. 

**I am currently in CSCI-33a, so maybe my fix is naive or perhaps I have diagnosed the problem wrong all together!**

**Comment by latefield** [comment]
I have submitted a pull request which I believe will solve the problem, though unfortunately I did not have time to get the jekyll build environment up and running so while I confirmed that it returns "false" in conditions that I expect, I cannot confirm that #158 _actually_ fixes the issue.

I hope that this is helpful and thanks in advance for your feedback.

**Comment by dmalan** [comment]
Closed by https://github.com/cs50/jekyll-theme-cs50/pull/158 (albeit with a bug of my own, fixed in a newer commit). Thanks!
