### ISSUE TITLE
Requesting Collapsible Sidebar

### ISSUE THREAD

**Issue by SarveshMD** [cs50/jekyll-theme-cs50#189]
Making the sidebar collapsible would be a really good feature to make reading the problem instructions more centered and easily zoomable. Adding a shortcut to collapse and expand the sidebar is the even better.

**Comment by dmalan** [comment]
Currently not possible full-screen, but if you shrink the window to 2/3 or so of your viewport, the sidebar should automatically jump to the top, allowing for side-by-side layouts! We'll keep this in mind, though!

**Comment by SarveshMD** [comment]
Great! Thanks.
